### ISSUE TITLE
Trying to accomplish the same

### ISSUE THREAD

**Issue by ArnaudJeannin** [maxbause/next-graphql-styled-components-ts-boilerplate#1]
Thanks a lot for your tutorial, it helps me a lot!

I'm trying to accomplish the same for my blog. Works well but it's not SSR. Do you know where I'm wrong?

https://github.com/Kernn-io/website

**Comment by maxbause** [comment]
I'm happy to hear that @ArnaudJeannin !

I have checked https://metierinterim.now.sh/ and it renders on the server side. (view-source:https://metierinterim.now.sh/)

Why do you think it doesn't SSR?

**Comment by maxbause** [comment]
Got it now!
I have opened a new issue in your project: https://github.com/Kernn-io/website/issues/1
