### ISSUE TITLE
Pure Javascript version

### ISSUE THREAD

**Issue by eugeneross** [maxbause/next-graphql-styled-components-ts-boilerplate#4]
I would be interested in seeing a pure javascript version of this, but I know that's a big ask. However, I'm curious about what the javascript alternative would be for this line:  

`<JobList jobs={jobs?.data?.jobs || []} />`

https://github.com/maxbause/next-graphql-styled-components-ts-boilerplate/blob/master/pages/index.tsx#L28

**Comment by maxbause** [comment]
Hi Eugene,
the pure javascript alternative would look something like this: 

```jsx
...

let jobArray = []
if(jobs && jobs.data && jobs.data.jobs) {
  jobArray = jobs.data.jobs
}

return (
  <JobList jobs={jobArray} />
)

...
```

The "?" is used for optional chaining and was introduced in TypeScript 3.7.
